# Replace these lines:
remote_theme: sighingnow/jekyll-gitbook
baseurl: '/thegreenroom/docs'

# With:
theme: jekyll-theme-primer  # Use GitHub's default temporarily
baseurl: ''  # Empty for root-level deployment