source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Core
gem "jekyll"

# Plugins
gem 'jekyll-remote-theme'
gem 'jekyll-feed'
gem 'jekyll-readme-index'
gem 'jemoji'

# Windows compatibility
gem 'webrick'


